import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/organism/Header/Header";

export const metadata: Metadata = {
  title: "Car hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <Header />
        {children}
      </body>
    </html>
  );
}
